FROM maven:3.9.9-eclipse-temurin-8

WORKDIR /app

COPY maven-settings.xml /usr/share/maven/conf/settings.xml
COPY app/pom.xml /app/pom.xml

RUN mvn -q -DskipTests dependency:go-offline

COPY app /app

EXPOSE 8080

CMD ["mvn", "spring-boot:run"]